### ISSUE TITLE
Fatal error: Cannot redeclare fathom_get_url()

### ISSUE THREAD

**Issue by infotexture** [usefathom/wordpress-plugin#2]
On a site running WordPress 4.9.10 with PHP 5.6.40, the following error appears when activating plug-in version 1.0.1:

> Plugin could not be activated because it triggered a fatal error.
> 
> **Fatal error:** Cannot redeclare `fathom_get_url()` (previously declared in /var/www/virtual/username/html/wp-content/plugins/fathom-analytics/fathom-analytics.php:32) in **/var/www/virtual/username/html/wp-content/plugins/fathom-analytics/fathom-analytics.php** on line **32**

**Comment by JackEllis** [comment]
Hi Roger - PHP 5.6 has reached end of life so we don't support it.
