### ISSUE TITLE
Feature request: Integrate analytics dashboard into WP dashboard

### ISSUE THREAD

**Issue by StuartMorrisAU** [usefathom/wordpress-plugin#3]
It’d be useful if the hosted analytics dashboard could be added as a full-screen-width widget to the WordPress backend dashboard, similar to what MonsterInsights do for Google Analytics. This would allow me to quickly see my stats when I log in to WordPress without needing to go fetch them from another website.

**Comment by JackEllis** [comment]
@StuartMorrisAU We have added a page for this now!
