### ISSUE TITLE
How do you defer script ?

### ISSUE THREAD

**Issue by oguilleux** [usefathom/wordpress-plugin#6]
I've installed your plugin and was wondering how you would add defer to the script tag ? You don't seem to be using wp_enqueue_script, is there a reason ? 

Thanks for your reply

**Comment by chuckreynolds** [comment]
commented similar in a PR here https://github.com/usefathom/wordpress-plugin/pull/9#issuecomment-1765484212

**Comment by chuckreynolds** [comment]
Reference: https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/

**Comment by JackEllis** [comment]
PR from @joedawson fixed it thank you!
