### ISSUE TITLE
Releases out of sync with WP.org?

### ISSUE THREAD

**Issue by jeffpaul** [usefathom/wordpress-plugin#8]
Looks like the [releases here on GitHub](https://github.com/usefathom/wordpress-plugin/releases) our out of sync with those on [WP.org](https://wordpress.org/plugins/fathom-analytics/).  Perhaps there's a different source repo for the WP.org plugin?

**Comment by JackEllis** [comment]
Sorted it, @jeffpaul, sorry for the delay, we're dialing in focus on the WP plugin moving forward
